### PR TITLE
fix: fixed an issue that the taskState doesn't get updated

### LINKED ISSUE #44: Fix Edit Task State UI
- the edit task state UI doesn't work as indented and always gives errors to the user when using it.

### PR DESCRIPTION
**Pull request by YoussefmSaber**
## 📃 Fixes:
- This pr closes #44 issue
- now the task state can be updated without any issues

### CODE REVIEW

File: src/main/kotlin/data/repositories/projectstates/ProjectStatesRepositoryImp.kt [hunk 1]
```diff
@@ -21,7 +21,8 @@ class ProjectStatesRepositoryImp(
         return dataSource.getStateById(stateId)
     }
 
-    override suspend fun editState(stateId: UUID, newState: TaskStateEntity) {
+    override suspend fun editState(newState: TaskStateEntity) {
+        println("Repository: State updated successfully: $newState")
         dataSource.editState(newState)
```
Comment (haideraljawasim) [inline src/main/kotlin/data/repositories/projectstates/ProjectStatesRepositoryImp.kt]: delete this print statement

**Review by haideraljawasim — APPROVED** [review]

**Review by ABDULLAHHG — APPROVED** [review]
